### ISSUE TITLE
Need an incomplete list of top level objects

### ISSUE THREAD

**Issue by fffej** [fffej/sql-server-gen#33]
A `Service` has a `Queue`.

Therefore if I list `Queue` in `Database` then QuickCheck is going to generate a shit load of them; both dependent and leaves.  I should eliminate dependent objects from the top-level database objects.

**Comment by fffej** [comment]
This is evidenced by the sheer number of `Certificate` created!

**Comment by fffej** [comment]
I think the work of @SuperDrew in the CLI with the flags issue solves this nicely.

**Comment by SuperDrew** [comment]
tk :+1:
