### ISSUE TITLE
Add ability to write out database to a scripts folder

### ISSUE THREAD

**Issue by fffej** [fffej/sql-server-gen#62]
CC @SuperDrew 

Writing out to a scripts folder should be pretty straight-forward.  Here's a rough attempt at how I'd do it.

```
-- This is the top level function.  Take a database, a directory and write it out
writeScriptsFolder :: Database -> DirectoryPath -> IO ()

-- represents a single entry
data ScriptFolderEntry = ScriptFolderEntry RelativePath String

-- Turn a given list of entities into a list of script folder things
renderEntities :: Entity a => [a] -> [ScriptFolderEntry]

-- Write the whole lot to disk
writeScriptFolderEntries :: FilePath -> [ScriptFolderEntry] -> IO ()
```

If you're feeling adventurous, you can probably hook up some additional functionality in the `Entity` type class (perhaps having the name of the folder encoded in there would be good)./

I'd probably add an option to the CLI to hook it into this too!  

For most objects, there's minimal complexity and I think the form is correct for SQL Compare to consume.

Happy to give more thoughts or pair on doing it.

**Comment by SuperDrew** [comment]
@fffej awesome, thank you.  Would be keen to pair or triple on this with @GrahamTheCoder.

**Comment by fffej** [comment]
Happy to pair, just grab some time in my calendar.

**Comment by SuperDrew** [comment]
We decided this wasn't the right way to go.  
- It isn't actually required for the testing we are doing. 
- It pollutes this project with specifics not related to sql.

@fffej I'm happy for this to be closed.
