### ISSUE TITLE
Add info on exclusions into header for file

### ISSUE THREAD

**Issue by SuperDrew** [fffej/sql-server-gen#65]
Currently the header for generated files with the cli binary include the seed and size used but not the exclusions.  They should be added.

e.g.
    -- This code was generated by sql-server-gen
    -- Arguments used: seed=12344 size=10

Should be
     -- This code was generated by sql-server-gen
    -- Arguments used: seed=12344 size=10 exclusions="PF"

As a start the strings are fine, at some point indicating what they mean would be better.

**Comment by SuperDrew** [comment]
Put in a PR for this, it's tiny.

**Comment by fffej** [comment]
#67 completed this work, awesome!
